name: Build, Test and Push Go Image

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: 1.24.2

      # 3. Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 4. Run Go tests
      - name: Run tests
        run: |
          go test ./... -v -cover

      # 5. Set up QEMU for multi-arch builds
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.6.0

      # 6. Set up Docker Buildx
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.10.0

      # 7. Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      # 8. Build and push Docker image
      - name: Build and push Go image
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/danielbutlerismyname/go-api:latest
            ghcr.io/danielbutlerismyname/go-api:${{ github.sha }}
